### ISSUE TITLE
Super Mario Sunshine button mapping (Wii u Pro, classic pro)

### ISSUE THREAD

**Issue by user18081972** [libertyernie/Nintendont#7] opened 2023-10-07 11:40 UTC
It makes sense to automatically apply LI_SHOULDER=1 when playing Mario Sunshine.

Because, ~~Z button is not used in the game.~~
The game relies on analog triggers for F.L.U.D.D., the game gets unnecessarily difficult without it.

~~Again, since Z is not used, nothing is lost by enabling it by default.~~

**Comment by IsaacSchemm** [comment] 2023-10-10 20:44
Do you know of any other games that do not use the Z button? It may be helpful to apply logic like this to multiple games at once, given that there's a limit on how big the Nintendont code can be (I think it needs to fit in the area of Wii RAM not used by the GameCube game).

**Comment by libertyernie** [comment] 2023-10-10 20:45
Do you know of any other games that do not use the Z button? It may be helpful to apply logic like this to multiple games at once, given that there's a limit on how big the Nintendont code can be (I think it needs to fit in the area of Wii RAM not used by the GameCube game).

**Comment by user18081972** [comment] 2023-10-11 09:50
Sorry, I just discovered i was wrong. because i blindly believed someone on reddit saying Z was completely unused. the Z button is used to open the "[Guide Book](https://www.mariowiki.com/Guide_Book )". 

Although the guide book is mostly unnecessary/not as important as using FLUDD while running, ~~to prevent confusion and frustration it might be better to not automatically apply that change.~~

I also do not know of any games that don't use the Z button.

**Comment by NintendoManiac64** [comment] 2023-10-11 21:28
May I ask what this suggestion would do in the context of issue #4?  The main thing is that, to be honest, I have no idea what `LI_SHOULDER=1` means.

Also I would think that having the guide book mapped to select aka minus would be a good location since both buttons are seldomly used since your left thunb primarly uses the analog stick the whole time anyway.

**Comment by user18081972** [comment] 2023-10-12 15:13
> May I ask what this suggestion would do in the context of issue #4?

Oh it seems this issue (#7) is essentially a duplicate of #4.


> Also I would think that having the guide book mapped to select aka minus would be a good location since both buttons are seldomly used since your left thunb primarly uses the analog stick the whole time anyway.

You are completely correct! I forgot that LI_Shoulder being on (=1) would map Z to SELECT. Which is a completely fine compromise. I got myself under the assumption that Z would be totally unmapped.

So I see no downsides to automatically enabling LU_SHOULDER when playing Super Mario Sunshine, or as you suggest in #4 also in Luigi's mansion,


>  I have no idea what `LI_SHOULDER=1` means.

LI_SHOULDER is an option in this fork of Nintendont that remaps buttons for some controllers as follows as follows:

Classic Controller:
L -> L (analog)
R -> R (analog)
ZL -> half L press (0x7F)
ZR -> half R press (0x7F)
Home -> Start (if LI_NOEXIT is used)
Select -> Z
Classic Controller Pro / Wii U GamePad:
ZL -> full L press (0xFF)
ZR -> full R press (0xFF)
L -> half L press (0x7F)
R -> half R press (0x7F)
Home -> Start (if LI_NOEXIT is used)
Select -> Z

**Comment by libertyernie** [comment] 2023-10-28 19:46
LI_SHOULDER is already be enabled in the versions of Nintendont I'm posting, but its effect is overridden by LI_CUSTOM_CONTROLS, as requested in #4. Do you think it makes sense to keep #4 or to revert it? I haven't played either of these games myself.

**Comment by NintendoManiac64** [comment] 2023-10-28 20:04
I suppose the only real difference then are just the "small" shoulder buttons being at 254/255 instead of the 127/255 as is used by default.

But I'm concerned that, for Luigi's Mansion and Mario Sunshune, 127/255 may not be enough because they basically have two different functions that occur with 254/255 and 255/255, therefore I believe 127/255 would simply be a weaker version of 127/255.

**Comment by libertyernie** [comment] 2023-10-28 21:47
See if this works: https://github.com/libertyernie/Nintendont/releases/tag/v20231028

**Comment by NintendoManiac64** [comment] 2023-10-29 20:30
> See if this works: https://github.com/libertyernie/Nintendont/releases/tag/v20231028

Two bits of feedback:

1. You typo'd the name and put 2022 as the year :P

2. Is that the Xbox 360 wired controller version of the build? I say this because it always throws up an error saying it can't find the game in the USB path despite the previous version not having this issue.

I know it's been a while so maybe you don't remember, but Xbox 360 wired controller support replaces USB storage support, so you really want to post versions both with and without 360 controller support. Therefore, in the process of renaming the title to say 2023, maybe also rename it to say something like Xbox 360 pad and optionally SD card only?

The main issue is that, on my own personal Wii, I use USB storage because I need to use a non-HC SD card for specifically Excite Truck (unless someone figured out a mod to add SDHC support? Nothing's coming up in internet searches...), and I personally don't care all that much about 360 controller support.  However, I have a family friend that basically exclusively uses an wired 360 controller for GameCube games and has a 256GB SDXC card for Wii homebrew stuff.

**Comment by libertyernie** [comment] 2023-10-30 00:05
This is the version with Xbox 360 controller support (and without USB storage support). I'll post a version later without it if there are no problems with this one. In the future, though, I might not put out a build with Xbox 360 controller support if the only changes were to Classic Controller or GamePad mappings.

**Comment by NintendoManiac64** [comment] 2023-10-30 00:19
>  In the future, though, I might not put out a build with Xbox 360 controller support if the only changes were to Classic Controller or GamePad mappings.

That's unfortunate since this aforementioned family friend is in fact using a Wii U (hence the use of an SD card rather than a USB drive) and is what I was going to be using to test the Wii U gamepad functionality (which I *still* haven't tested because, the last time we got together, they visited us and I don't have a Wii U, so...)

That being said, there's really only like one or two more things I have in mind, that being the optional things I previously mentioned anyway which, now that I think of it, I may actually want to have gamepad support re-introduced and then have the optional thing(s) I have in mind *not* apply to the gamepad (if this is even possible?). I'm guessing that'd require removing mappings for other games, but that's fine since you can set a separate loader.dol for a given game in USB Loader GX.

　
>  I'll post a version later without it if there are no problems with this one.

I know it's a bit late now, but doesn't it make more sense to post the one without the Xbox 360 controller support first? That way it's easier to test with since it would support both USB drives and SD cards without the need to temporarily rig up a large-enough SD card purely for testing purposes for people (e.g. myself) that have games stored on a USB drive instead.

**Comment by libertyernie** [comment] 2023-10-30 15:16
To be honest, it's been so long - and I spent so much time [figuring out this issue](https://github.com/FIX94/Nintendont/issues/1121) - that I forgot there were two different versions when I built this one. I'll compile and post the other one later today.

**Comment by NintendoManiac64** [comment] 2023-11-09 01:48
> I'll compile and post the other one later today.

I finally got around to testing, and I have some feedback that I've posted particularly on issues #3, #4, and #6:

> I think I might have made a typo or two on [SpyHunter's] button arrangement and mixed up a couple of the Ls and Rs...
> 
> Amusingly though, the actual result in build 2023-10-30 seems to not be what I typo'd nor what I had originally intended, but a third configuration altogether.
> 
> So I've reworked the listed custom controls for this game, and the end result should actually be something that takes up less space in Nintendont (in particular I've removed the custom mapping for the "big" L button on CC/pro).
> 
> Also, if it saves space in Nintendont, you can optionally leave out the `CC/pro_select/minus = GC_X`

————————

> It would seem that I forgot to account that the "big" and "small" L buttons need to be reversed for [Luigi's Mansion and Mario Sunshine] unlike the R/ZR buttons; that is:
> 
>     * "large" L button on CC/pro = GC_L digital press
> 
>     * "small" L button on CC/pro = GC_L analog press @ 254/255
> 
> 
> I've modified the first post accordingly.



————————

> Turns out that using the R or L button on their own isn't really used in [Mario Kart Double Dash's] menus at all, so we should be able to make left and right on the Dpad work even in the menus if we simply add a bit of an analog stick tilt (though I'm uncertain how much; it seems to need a bit less than half, maybe 40%?)
> 
> That being said, we're already using 127/255 (aka 50%) for Smash Bros Melee, so I don't suppose we're able to save space if we had both Melee and Double Dash using the same value specifically for left & right Dpad/analog stick (but _not_ up & down Dpad/analog stick)?
> 
> But if we're not able to save space by consolidating, then I'd prefer trying something like 100/255 to start off with, i.e.:
> 
>     * Dpad_left on CC/pro = GC_L digital press + GC_left-analog left @ 100/255
> 
>     * Dpad_right on CC/pro = GC_R digital press + GC_left-analog right @ 100/255

**Comment by libertyernie** [comment] 2023-12-09 23:04
Closed as duplicate of #4

**Closed as completed by libertyernie** 2023-12-09 23:04 UTC
